FROM python:3.10-slim

WORKDIR /app

# Cai dat cac thu vien he thong can thiet cho OpenCV va AI
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
