name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Kiem tra cu phap Docker Compose
      run: docker-compose config
      
    - name: Kiem tra Build (Backend & AI Worker)
      # Chi build thu backend va worker de tiet kiem thoi gian CI
      run: docker-compose build backend_api ai_worker
