events { worker_connections 1024; }
http {
    server {
        listen 80;
        location / { proxy_pass http://frontend_kiosk:80; }
        location /api/ { 
            proxy_pass http://backend_api:8000/;
            # Cấu hình Upgrade để Nginx cho phép WebSocket đi qua
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
    server {
        listen 8080;
        location / { proxy_pass http://frontend_admin:80; }
        location /api/ { proxy_pass http://backend_api:8000/; }
    }
}
