events { 
    worker_connections 1024; 
}

http {
    # Server cho Kiosk (Cong 80)
    server {
        listen 80;
        
        # Dieu huong vao giao dien Kiosk
        location / { 
            proxy_pass http://frontend_kiosk:80; 
        }
        
        # Dieu huong vao Backend API kem theo WebSocket
        location /api/ { 
            proxy_pass http://backend_api:8000/;
            
            # Giu nguyen IP that cua Client gui xuong Backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Cau hinh Upgrade de Nginx cho phep WebSocket đi qua
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Server cho Admin Portal (Cong 8080)
    server {
        listen 8080;
        
        # Dieu huong vao giao dien Admin
        location / { 
            proxy_pass http://frontend_admin:80; 
        }
        
        # Dieu huong API tu Admin vao Backend
        location /api/ { 
            proxy_pass http://backend_api:8000/; 
            
            # Giu nguyen IP that cua Client
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
