events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # 1. Điều phối Frontend (Trang Web)
        location / {
            proxy_pass http://frontend_web:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Điều phối Backend (API)
        location /api/ {
            proxy_pass http://backend_api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
